//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public string emp_id { get; set; }
        public string ename { get; set; }
        public System.DateTime dob { get; set; }
        public string guardian { get; set; }
        public System.DateTime doj { get; set; }
        public string bpay { get; set; }
        public string deptid { get; set; }
        public string desigid { get; set; }
        public string placeid { get; set; }
        public string districtid { get; set; }
    }
}
